Update spark-job
Changing the job trigger values. 
Committing changes to address the below exception:
java.lang.ClassNotFoundException: app/ihealth_anomaly_detection.py